# This is a basic workflow to help you get started with Actions

name: Make Compatibility Font

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install fonttools
        
      - name: Build
        run: |
          # find the directory of the latest version
          export target_dir=$(ls -d */ | cut -f1 -d'/' | sort -V | tail -n1)
          # call the build script
          for f in "$target_dir"/I.Ming*CP-*.ttf; do
            python3 .github/workflows/converter.py "$f"
          done

      - name: Upload
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Convert compatibility font files"
            git push
          fi
